code/colocacion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('jobs.urls', namespace="jobs")),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^users/', include('users.urls', namespace="users"))
]

code/jobs/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
     url(r'^jobsapplied/$', views.jobs, name='jobsapplied'),
     url(r'^dashboard/(?P<filters>[\w\-]+)/$', views.dashboard, name='dashboard'),
     url(r'^job_detail/(?P<job_id>\d+)/$', views.job_detail, name='job_detail'),
     url(r'^apply/(?P<job_id>\d+)/$', views.apply, name="apply"),
]

code/users/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

     url(r'^profile/$', views.profile, name='profile'),
     url(r'^profileedit/$', views.profileedit, name='profileedit'),
     url(r'^tests/$', views.tests, name='tests'),
     url(r'^taketests/(?P<tlevel>[a-z]+)/$', views.taketests, name='taketests'),
     url(r'^countmarks/(?P<test_id>[0-9]+)/(?P<question_id>[0-9]+)/$', views.countmarks, name='countmarks'),
     url(r'^question/(?P<testid>[0-9]+)/(?P<questionid>[0-9]+)/$', views.question, name='question'),
     url(r'^results/$', views.results, name="results"),
     url(r'^answers/(?P<test_id>[0-9]+)/$', views.answers, name="answers"),
     url(r'^logout/$', views.logout, name="logout"),
     url(r'^changepassword/$', views.changepassword, name="changepassword"),
]

code/jobs/models.py
from django.db import models
from accounts.models import UserDetails

# Create your models here.
class Jobs(models.Model):
	JOBCLASS=(
		('A','A'),
		('B','B'),
		('C','C'),
		)
	job_id = models.AutoField(primary_key=True)
	job_role = models.CharField(max_length=500)
	job_title = models.CharField(max_length=300, unique=True, blank=False)
	job_type = models.CharField(max_length=100)
	experience_required = models.IntegerField()
	company_name = models.CharField(max_length=50, blank=False)
	salary = models.IntegerField(blank=False)
	location = models.CharField(max_length=500)
	skills_set = models.CharField(max_length=1000)
	job_class = models.CharField(max_length=1, choices=JOBCLASS)
	desc = models.TextField(blank=False)
	def __str__(self):
	    return (self.job_title)

class JobsApplied(models.Model):
	email = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
	job_id = models.ForeignKey(Jobs, on_delete=models.CASCADE)
	def __str__(self):
	    return str(self.job_id)

code/users/models.py
from django.db import models
from accounts.models import UserDetails

class Tests(models.Model):
	LEVELS=(
		('easy','easy'),
		('medium','medium'),
		('difficult','difficult'),
		)
	test_id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=300, blank=False)
	level = models.CharField(max_length=10,choices=LEVELS)
	total_marks = models.IntegerField()
	def __str__(self):
		return self.title

class TestsTaken(models.Model):
	email = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
	test_id = models.ForeignKey(Tests, on_delete=models.CASCADE)
	marks_obtained = models.IntegerField(default=0)

class Questions(models.Model):
	class Meta:
		unique_together = (("test_id","question_id"),)
	test_id = models.ForeignKey(Tests, on_delete=models.CASCADE)
	question_id = models.IntegerField()
	question_text = models.CharField(max_length=1000)
	correct_choice = models.CharField(max_length=1000)
	def __str__(self):
	    return str(self.question_text)

class Choice(models.Model):
	class Meta:
		unique_together = (("test_id","question_id","choice_id"),)
	test_id = models.ForeignKey(Tests, on_delete=models.CASCADE)
	question_id = models.ForeignKey(Questions, on_delete=models.CASCADE)
	choice_id = models.IntegerField()
	choice_text = models.CharField(max_length=1000)
	def __str__(self):
	    return self.choice_text

class Answers(models.Model):
	class Meta:
		unique_together = (("email","test_id","question_id"),)
	test_id = models.ForeignKey(Tests, on_delete=models.CASCADE)
	email = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
	question_id = models.ForeignKey(Questions, on_delete=models.CASCADE)
	choice_id_selected = models.CharField(max_length=1000)
	def __str__(self):
	    return str(self.choice_id_selected)  

code/jobs/views.py
from django.shortcuts import render, redirect
from .models import *
from users.models import *
from accounts.models import *
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from scipy import spatial
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def jobs(request):
	if 'email' in request.session:
		if JobsApplied.objects.filter(email=request.session['email']).exists():
			jobsapplied = JobsApplied.objects.filter(email=request.session['email']).values('job_id',
				'job_id__job_title', 'job_id__salary', 'job_id__job_role', 'job_id__experience_required',
				'job_id__job_type',)
			return render(request, 'jobs/jobsapplied.html', {'jobs':jobsapplied})
		else:
			return render(request, 'jobs/jobsapplied.html',{'message':"No jobs applied"})
	else:
		return redirect('/accounts/login')

def job_detail(request, job_id):
	job = Jobs.objects.get(job_id=job_id)
	if JobsApplied.objects.filter(email=request.session['email'], job_id=job_id).exists():
		message = "disable"
	else:
		message = "enable"
	return render(request, 'jobs/job_detail.html',{'job':job, 'message':message})

def apply(request, job_id):
	job = JobsApplied(email=UserDetails.objects.get(pk=request.session['email']),
		job_id=Jobs.objects.get(job_id=job_id))
	job.save()
	return redirect('/jobs/jobsapplied')

def dashboard(request, filters):
	jc = "None"
	#job-job collaborative filtering algorithm
	if JobsApplied.objects.filter(email=request.session['email']).exists():
		jobs_exclude = JobsApplied.objects.filter(email=request.session['email'])
		exclude_id = []
		for job in jobs_exclude:
			exclude_id.append(job.job_id)
		df = pd.DataFrame(list(Jobs.objects.all().values()))
		df_exclude = pd.DataFrame(list(jobs_exclude.values()))
		cvCompName = CountVectorizer()
		cvDesc =CountVectorizer()
		cvJobClass = CountVectorizer()
		cvJobRole = CountVectorizer()
		cvJobTitle = CountVectorizer()
		cvJobType = CountVectorizer()
		cvLocation = CountVectorizer()
		cvSkills = CountVectorizer()
		
		cvCompNameVal = cvCompName.fit_transform(df["company_name"].tolist())
		cvDescVal=cvDesc.fit_transform(df["desc"].tolist())
		cvJobRoleVal = cvJobRole.fit_transform(df["job_role"].tolist())
		cvJobTitleVal = cvJobTitle.fit_transform(df["job_title"].tolist())
		cvJobTypeVal = cvJobType.fit_transform(df["job_type"].tolist())
		cvLocationVal = cvLocation.fit_transform(df["location"].tolist())
		cvSkillsVal = cvSkills.fit_transform(df["skills_set"].tolist())
		salary=df["salary"].values
		salary=salary/float(max(salary))
		salary=salary.reshape(len(salary),1)
		experience=df["experience_required"].values
		experience=experience/float(max(experience))
		experience=experience.reshape(len(experience),1)
		finalnp=list(np.concatenate((cvCompNameVal.toarray(), cvDescVal.toarray(),cvJobRoleVal.toarray(),
			cvJobTitleVal.toarray(),cvJobTypeVal.toarray(),cvLocationVal.toarray(),cvSkillsVal.toarray(),salary,experience), axis=1))
		
		df_applied = pd.DataFrame(list(JobsApplied.objects.filter(email=request.session['email']).values('job_id',
					'job_id__company_name', 'job_id__desc', 'job_id__job_role', 'job_id__job_title', 
					'job_id__job_type','job_id__location','job_id__skills_set','job_id__salary','job_id__experience_required')))
		
		cvCompNameUser = cvCompName.transform(df_applied["job_id__company_name"].tolist())
		cvDescUser=cvDesc.transform(df_applied["job_id__desc"].tolist())
		cvJobRoleUser = cvJobRole.transform(df_applied["job_id__job_role"].tolist())
		cvJobTitleUser = cvJobTitle.transform(df_applied["job_id__job_title"].tolist())
		cvJobTypeUser = cvJobType.transform(df_applied["job_id__job_type"].tolist())
		cvLocationUser = cvLocation.transform(df_applied["job_id__location"].tolist())
		cvSkillsUser = cvSkills.transform(df_applied["job_id__skills_set"].tolist())
		salaryUser=df_applied["job_id__salary"].values
		salaryUser=salaryUser/float(max(salaryUser))
		salaryUser=salaryUser.reshape(len(salaryUser),1)
		experienceUser=df_applied["job_id__experience_required"].values
		experienceUser=experienceUser/float(max(experienceUser))
		experienceUser=experienceUser.reshape(len(experienceUser),1)

		finalnpUser=list(np.concatenate((cvCompNameUser.toarray(), cvDescUser.toarray(),cvJobRoleUser.toarray(),
			cvJobTitleUser.toarray(),cvJobTypeUser.toarray(),cvLocationUser.toarray(),cvSkillsUser.toarray(),salaryUser,experienceUser), axis=1))
		similarity=np.array([[1-spatial.distance.cosine(i,j) for j in finalnp] for i in finalnpUser])
		exc=list(df_exclude["job_id_id"].values)
		scores=np.sum(similarity,axis=0)
		predictions=list(reversed(np.argsort(scores)))
		predictions=[i+1 for i in predictions]
		finalpred=[i for i in predictions if i not in exc]

		#user-user collaborative filtering algorithm
		df_col = pd.DataFrame(list(JobsApplied.objects.all().values()))
		emails=list(set(df_col["email_id"].tolist())) 
		jobids=list(set(df_col["job_id_id"].tolist()))
		zeroarray=np.zeros((len(emails),len(jobids)))
		colab_df=pd.DataFrame(zeroarray, index=emails, columns=jobids)
		for i in emails:
			df_temp=df_col[df_col["email_id"]==i]
			jobid=df_temp["job_id_id"].tolist()
			for j in jobid:
				colab_df.ix[i,j]=1
		curemail=request.session['email']
		otherusersemail=[i for i in emails if i not in curemail]
		currentUser=list(colab_df.ix[curemail,:])
		otherUser=list(colab_df.ix[otherusersemail,:].values)		
		mostsim=[]
		for i in otherUser:
			mostsim.append(1-spatial.distance.cosine(currentUser,i))
		
		finalrecoset=[]
		finalreco=[0]*len(currentUser)
		usersreco=list(reversed(np.argsort(mostsim)))	
		for i in usersreco[:5]:
			usersjobs=list(otherUser[i])
			finalreco=list(np.array(usersjobs) - np.array(currentUser))
			for j in range(len(finalreco)):
				if finalreco[j]<0:
					finalreco[j]=0	
			finalrecoset.append(finalreco)	

		final=np.sum(finalrecoset,axis=0)	
		orderreco=list(reversed(np.argsort(final)));
		recommendations=[]
		for i in range(len(orderreco)):
			if orderreco[i]>0:
				recommendations.append(jobids[i])
		finalrecommendations=[i for i in recommendations if i not in exc]
		for jobid in finalpred:
			finalrecommendations.append(jobid)
		finaljobs = set(finalrecommendations)
	else:
		#content-based algorithm
		df = pd.DataFrame(list(UserProfile.objects.filter(email=request.session['email']).values('skills')))
		cvUserSkills = CountVectorizer()
		cvUserSkillsVal=cvUserSkills.fit_transform(df["skills"].tolist())
		finalskillsnp=list((cvUserSkillsVal.toarray()))

		dfjobs = pd.DataFrame(list(Jobs.objects.all().values('job_id','skills_set')))
		cvSkillsRequiredVal=cvUserSkills.transform(dfjobs["skills_set"].tolist())
		finalskillsrequirednp=list((cvSkillsRequiredVal.toarray()))

		similarity=np.array([[1-spatial.distance.cosine(i,j) for j in finalskillsnp] for i in finalskillsrequirednp])
		predictions = []
		count = 0
		for sim in similarity:
			count = count+1
			if sim>0:
				predictions.append(count)
		finaljobs = predictions

    #filtering by test results
	if TestsTaken.objects.filter(email=request.session['email']).exists():
		teststaken = TestsTaken.objects.filter(email=request.session['email'])
		marks = 0
		count = 0
		for test in teststaken:
			marks = marks + test.marks_obtained
			count = count + 1
		avg = (marks/count)
		if avg>=75:
			jc = 'A'
		elif avg>=45 and avg<75:
			jc = 'B'
		else:
			jc = 'C'

	#processing and rendering
	if jc != "None":
		if filters != "nofilter":
			if filters == "salary":
				final_jobs = Jobs.objects.filter(job_class = jc, job_id__in = finaljobs).order_by('-'+filters)[:15]
			else:
				final_jobs = Jobs.objects.filter(job_class = jc, job_id__in = finaljobs).order_by(filters)[:15]
		else:#when filters = nofilter
			final_jobs = Jobs.objects.filter(job_class = jc, job_id__in = finaljobs)[:15]
	elif jc == "None":#no tests are taken
		if filters != "nofilter":
			if filters == "salary":
				final_jobs = Jobs.objects.filter(job_id__in = finaljobs).order_by('-'+filters)[:15]
			else:
				final_jobs = Jobs.objects.filter(job_id__in = finaljobs).order_by(filters)[:15]
		else:#when filters = nofilters
			final_jobs = Jobs.objects.filter(job_id__in = finaljobs)[:15]

	paginator = Paginator(final_jobs, 3)
	page = request.GET.get('page')
	try:
		jobs = paginator.page(page)
	except PageNotAnInteger:
		jobs = paginator.page(1)
	except EmptyPage:
		jobs = paginator.page(paginator.num_pages)
	if len(jobs)>0:
		return render(request, 'jobs/dashboard.html',{'jobs': jobs})
	else:
		return render(request, 'jobs/dashboard.html',{'message':"No jobs available right now!"})

code/users/templates/users/answers.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container" style="margin-top: 20px;width: 800px;">
  <div class="panel panel-default">
    <div class="panel-heading" style="background-color:#012951;color:white; text-align: center"><h2>Your Results</h2></div>
    <div class="panel-body" style="overflow: auto;">
        <h5 style="text-align: center">{{message}}</h5>

          {% for test in tests %}  

            <a href="{% url 'users:answers' test_id=test.test_id %}"><h3 for="test{{ forloop.counter }}">{{ test.test_id__title }}</h3></a>
            <h4>Level: {{ test.test_id__level }}&nbsp Your score: {{ test.marks_obtained }} out of {{ test.test_id__total_marks }}</h4>
            <br>

          {% endfor %}

          {% for question in questions %}
             <b>{{ forloop.counter }}. {{ question.question_text }}</b>
               <br><br>

             {% for choice in question.choice_set.all %}
                <input type="radio" value="{{ choice.id }}" disabled />
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>

                {% if choice.choice_text == question.correct_choice %}
                  <span class="glyphicon glyphicon-ok" style="color:green"></span>
                {% endif %} 


                {% for answer in answers %}            
                    {% if answer.choice_id_selected == choice.choice_text %}
                      {% if answer.choice_id_selected != question.correct_choice %}
                        <span class="glyphicon glyphicon-remove" style="color:darkred"></span>
                      {% endif %}
                    {% endif %}
                {% endfor %}</br>


              {% endfor %} <br>
          {% endfor %}

    </div>
    </div>
  </div>
</div>
{% endblock %}

code/users/templates/users/base.html
{% load static %}
<html>
<head>
  <title>Colocacion</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'users/tests.css' %}" >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function() {
        // messages timeout for 10 sec 
        setTimeout(function() {
            $('.message').fadeOut('slow');
        }, 1500); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        $('.del-msg').live('click',function(){
            $('.del-msg').parent().attr('style', 'display:none;');
        })
    });
 </script>
  </head>
  <body>
  <nav class="navbar navbar-inverse-right" data-spy="scroll" data-offset-top="197" style="background-color:#012951;height:70px;color:white;padding-top:10px; font-size:20px";>
  <div class="container-fluid">
<div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
		  <span class="icon-bar"></span>                        

      </button>
      <a class="navbar-brand" href="#">COLOCACION</a>
    </div>
    <div>
      <div class="collapse navbar-collapse" id="myNavbar" style="color:white";>
        <ul class="nav navbar-nav navbar-right" >
         <li class="active"><a href="{% url 'jobs:dashboard' filters='nofilter' %}">DASHBOARD</a></li>
          <li><a href="{% url 'users:profile' %}">PROFILE</a></li>
          <li ><a href="{% url 'users:tests' %}">TESTS</a></li>
          <li ><a href="{% url 'jobs:jobsapplied' %}">JOBS</a></li>
      <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
		</ul>
		
		  </div>
		  </div>
		  </div>
</nav>

<div class="container">
{% if messages %}
  <div class="row">
    <div class="message">
    {% for message in messages %}
    <p 
    {% if message.tags == "success" %} class="alert alert-success" {% endif %} 
    {% if message.tags == "error" %} class="alert alert-danger" {% endif %} 
    {% if message.tags == "info" %} class="alert alert-info" {% endif %} 
    {% if message.tags == "warning" %} class="alert alert-warning" {% endif %} 
    >{{ message }}</p>
    {% endfor %}

    </div>
  </div>
{% endif %}
</div>

{% block content %}
{% endblock %}
</body>
</html>

code/users/templates/users/jobs.html
{% extends 'users/base.html' %}
{% block content %}
<div id="pricing" class="container-fluid">
 
  <div class="row slideanim">
    <div class="col-sm-8 col-xs-10">
      <div class="panel panel-default text-center">
        <div class="panel-heading" style="background-color:#012951;color:white">
          <h1>Jobs you have applied</h1>
        </div>
        <div class="panel-body">
       <h3>Job1</h3>
	   <h3>Description</h3>
	   <h3>Job2</h3>
	   <h3>Description</h3>
        </div>
        
      </div>      
    </div>       
    
  </div>
</div>
{% endblock %}

code/users/templates/users/profile.html
{% extends 'users/base.html' %}
{% block content %}

<div class="panel panel-primary "  style="margin-top:5px;margin-left:180px;margin-right:180px;" class="mainbox col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
	<div class="panel-heading" style="background-color:#012951">
        	<h3 class="panel-title">Profile</h3>
			 <div style="float:right; font-size: 85%; position: relative; top:-10px;color:white"><a id="signinlink" href="{% url 'users:profileedit' %}">EDIT</a></div>
	</div>
	<div class="panel-body">
        <form id="signupform" class="form-horizontal" role="form" >{% csrf_token %}
                  <div id="signupalert" style="display:none" class="alert alert-danger">
                               <p>Error:</p>
                                    <span></span>
                              </div>
                                    
                                <div class="form-group ">
                                    <label for="email" class="col-md-4 control-label">Email</label>
                                    <div class="col-md-4">
                                       {{form1.email}}
                                    </div>
                                </div>
								  <div class="form-group">
                                    <label for="name" class="col-md-4 control-label">Name</label>
                                    <div class="col-md-4">
                                        {{form1.name}}
                                    </div>
                                </div>
                            
                                    <div class="form-group">
                                    <label for="city" class="col-md-4 control-label">City</label>
                                    <div class="col-md-4">
                                        {{form1.city}}
                                    </div>
                                </div>
								 <div class="form-group">
                                    <label for="mobileno" class="col-md-4 control-label">Mobile No</label>
                                    <div class="col-md-4">
                                        {{form1.mobile_num}}
                                    </div>
                                </div>
								 <div class="form-group">
                                    <label for="clgname" class="col-md-4 control-label">College</label>
                                    <div class="col-md-4">
                                        {{form2.college_name}}
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="clgname" class="col-md-4 control-label">Branch</label>
                                    <div class="col-md-4">
                                      {{form2.branch}}
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="degree" class="col-md-4 control-label">Degree</label>
                                    <div class="col-md-4">
                                       {{form2.degree}}
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="degreepercent" class="col-md-4 control-label">Aggregate</label>
                                    <div class="col-md-4">
                                       {{form2.degree_percent}}
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="interpercent" class="col-md-4 control-label">Inter Percentage</label>
                                    <div class="col-md-4">
                                        {{form2.inter_percent}}
                                    </div>
                                </div>
								<div class="form-group">
                                    <label for="sscpercent" class="col-md-4 control-label">SSC  Percentage</label>
                                    <div class="col-md-4">
                                       {{form2.ssc_percent}}
                                    </div>
                                </div>
								                                                                <div class="form-group">
                                    <label for="skills" class="col-md-4 control-label">Skills</label>
                                    <div class="col-md-4">
                                      {{form2.skills}}
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label for="interests" class="col-md-4 control-label">Interests</label>
                                    <div class="col-md-4">
                                        {{form2.interests}}
                                    </div>
                                </div>
                               
                                <div class="form-group">
                                    <label for="experience" class="col-md-4 control-label">Password</label>
                                    <div class="col-md-4">
                                        <button button type="button" class="btn btn-success" onclick="location.href='{% url 'users:changepassword' %}'">Change password</button>
                                    </div>
                                </div>
	</div>
	 

								</form>
                                 
                              </div>
				</div>
				</div>
                                    
{% endblock %}                        

code/users/templates/users/question.html
<html>
<head>
  <title>Colocacion</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type = "text/javascript" >
   function preventBack(){window.history.forward();}
    setTimeout("preventBack()", 0);
    window.onunload=function(){null};
  </script>
  </head>
<body>
<div class="container" style="margin-top: 50px;width: 800px">
  <div class="panel panel-default">
    <div class="panel-heading" style="background-color:#012951;color:white">{{ test.title }}{{ test.test_id }}</div>
    <div class="panel-body">
      <h4>{{question.question_id}}. {{ question.question_text }}</h4>

			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			<form action="{% url 'users:countmarks' test_id=test.test_id question_id=question.question_id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
			    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" required/>
			    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
			{% endfor %}

            <input type="submit" class="btn btn-success" value="Save & Next">
       </form>
    </div>
    </div>
  </div>
</div>
</body>
</html>

code/users/templates/users/results.html
<html>
<head>
  <title>Colocacion</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type = "text/javascript" >
   function preventBack(){window.history.forward();}
    setTimeout("preventBack()", 0);
    window.onunload=function(){null};
  </script>
  </head>
<body>
<center>
<h2 style="margin-top: 50px;">Your Results for {{test.title}}</h2>
 <h3>{{marks}}/{{test.total_marks}}</h3>
 
<br>
<button type="button" class="btn btn-success" onclick="location.href='{% url 'users:tests' %}'">Finish</button>
<br><br>
<button type="button" class="btn btn-success" onclick="location.href='{% url 'users:answers' test_id=test.test_id %}'">See Full Report</button>
</center>
</body>
</html>

code/users/templates/users/taketests.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading" style="background-color:#012951;color:white">{{ test.title }}</div>
    <div class="panel-body">
       <ul>
        Instruction:
        <li>Total number of questions : 20 </li>
        <li>Time alloted : 20 minutes </li>
        <li>Each question carry 1 mark, no negative marks </li>
        <li>DO NOT refresh the page</li>
        All the best :-)
      </ul>
       <button type="button" class="btn btn-success" onclick="location.href='{% url 'users:question' testid=test.test_id questionid=question.question_id %}'">Start Test</button>
    </div>
    </div>
  </div>
</div>

{% endblock %}

code/users/templates/users/tests.html
{% extends 'users/base.html' %}
{% block content %}
<div id="pricing" class="container-fluid">
 
  <div class="row slideanim">
    <div class="col-sm-8 col-xs-10">
      <div class="panel panel-default text-center">
        <div class="panel-heading" style="background-color:#012951;color:white">
          <h1>My Tests</h1>
        </div>
        <div class="panel-body" style="text-align: left">
            <h5 style="text-align: center">{{message}}</h5>
            {% for test in tests %}            
            <a href="{% url 'users:answers' test_id=test.test_id %}"><h3 for="test{{ forloop.counter }}">{{ forloop.counter}}. {{ test.test_id__title }}</h3></a>
            <h5 style="margin-left: 30px;">Level: {{ test.test_id__level }}&nbsp Your score: {{ test.marks_obtained }} out of {{ test.test_id__total_marks }}</h5>
            <br>
          {% endfor %}
        </div>
        
      </div>      
    </div>     
    <div class="col-sm-4 col-xs-2">
      <div class="panel panel-default text-center">
        <div class="panel-heading" style="background-color:#012951; color:white">
          <h1>Take Tests</h1>
        </div>
        <div class="panel-body">
          <button type="button" class="btn btn-success btn-arrow-right" onclick="location.href='{% url 'users:taketests' tlevel='easy' %}'">EASY</button>
		      <button type="button" class="btn btn-success btn-arrow-right" onclick="location.href='{% url 'users:taketests' tlevel='medium' %}'">MEDIUM</button>
					<button type="button" class="btn btn-success btn-arrow-right" onclick="location.href='{% url 'users:taketests' tlevel='difficult' %}'">Difficult</button>
        </div>
       
      </div>      
    </div>       
    
  </div>
</div>
{% endblock %}